name: Release Charts
on:
  push:
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # v4.1.7 https://github.com/actions/checkout/tree/v4.1.7
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # v4.3.0 https://github.com/Azure/setup-helm/tree/releases/v4.3.0
      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112
        with:
          version: latest
      - name: Package Releases
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            if ! git diff --quiet HEAD~1 -- "$chart"; then
              CHART_NAME=$(basename "$chart")
              helm package "$chart" --destination .cr-release-packages --version "0.0.${DATE_TAG}-N"
            fi
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          version: 'v1.8.1'
          skip_packaging: true
          skip_existing: true
          packages_with_index: true
          config: ./.github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
